const express = require("express")
const router = express.Router()
const userController = require('../controllers/UserController')
const { authMiddleware, authUserMiddleware } = require("../../middleware/authMiddleware")
const validateObjectId = require("../../middleware/validateObjectId")
router.post('/sign-up', userController.createUser)
router.post('/sign-in', userController.loginUser)
router.post('/log-out', userController.logoutUser)
router.put('/update-user/:id',validateObjectId, userController.updateUser)
router.get('/getAll',  authMiddleware, userController.getAllUser)
router.delete('/:id',validateObjectId, authMiddleware, userController.deleteUser)
router.delete('/delete-many-user', authMiddleware, userController.deleteU)
router.get('/get-details/:id', validateObjectId, authUserMiddleware, userController.getDetailUser)
router.post('/refresh-token', userController.refreshToken)
module.exports = router
